/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liquidhub;

/**
 *
 * @author bharatPC
 */
public class PARKING_NEW extends javax.swing.JFrame {

    /**
     * Creates new form PARKING_NEW
     */
    public PARKING_NEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton44 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton42 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton41 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jButton1.setText("P1.1");
        jPanel2.add(jButton1);
        jButton1.setBounds(50, 50, 70, 110);

        jButton8.setText("P1.8");
        jPanel2.add(jButton8);
        jButton8.setBounds(250, 180, 70, 100);

        jButton4.setText("P1.4");
        jPanel2.add(jButton4);
        jButton4.setBounds(350, 50, 70, 110);

        jButton2.setText("P1.2");
        jPanel2.add(jButton2);
        jButton2.setBounds(150, 50, 70, 110);

        jButton10.setText("P1.10");
        jPanel2.add(jButton10);
        jButton10.setBounds(450, 180, 70, 100);

        jButton9.setText("P1.9");
        jPanel2.add(jButton9);
        jButton9.setBounds(350, 180, 70, 100);

        jButton7.setText("P1.7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(150, 180, 70, 100);

        jButton3.setText("P1.3");
        jPanel2.add(jButton3);
        jButton3.setBounds(250, 50, 70, 110);

        jButton6.setText("P1.6");
        jPanel2.add(jButton6);
        jButton6.setBounds(50, 180, 70, 100);

        jButton5.setText("P1.5");
        jPanel2.add(jButton5);
        jButton5.setBounds(450, 50, 70, 110);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Locality", "GACCHIBOWLI", "HI TECH", "BANJARA HILLS", "NECKLACE  ROAD" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(30, 320, 130, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Select your spot...");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 10, 102, 20);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(220, 140, 0, 60);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(330, 380, 200, 20);

        jLabel8.setText("TIME OUT :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(250, 390, 80, 20);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(320, 350, 180, 20);

        jLabel10.setText("TIME IN    :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(254, 360, 80, 20);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(320, 320, 190, 20);

        jLabel12.setText("DATE        :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(254, 330, 80, 20);

        jButton44.setText("BOOK");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton44);
        jButton44.setBounds(30, 380, 79, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 580, 420);

        jTabbedPane1.addTab("level 1", jPanel2);

        jPanel3.setLayout(null);

        jLabel14.setText("DATE        :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(254, 330, 80, 20);
        jPanel3.add(jLabel15);
        jLabel15.setBounds(320, 320, 190, 20);

        jLabel16.setText("TIME IN    :");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(254, 360, 80, 20);
        jPanel3.add(jLabel17);
        jLabel17.setBounds(320, 350, 180, 20);

        jLabel18.setText("TIME OUT :");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(250, 390, 80, 20);
        jPanel3.add(jLabel19);
        jLabel19.setBounds(330, 380, 200, 20);
        jPanel3.add(jLabel20);
        jLabel20.setBounds(220, 140, 0, 60);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Select your spot...");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(10, 10, 102, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Locality", "GACCHIBOWLI", "HI TECH", "BANJARA HILLS", "NECKLACE  ROAD" }));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(30, 320, 130, 20);

        jButton11.setText("P2.5");
        jPanel3.add(jButton11);
        jButton11.setBounds(450, 50, 70, 110);

        jButton12.setText("P2.6");
        jPanel3.add(jButton12);
        jButton12.setBounds(50, 180, 70, 100);

        jButton13.setText("P2.3");
        jPanel3.add(jButton13);
        jButton13.setBounds(250, 50, 70, 110);

        jButton14.setText("P2.7");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14);
        jButton14.setBounds(150, 180, 70, 100);

        jButton15.setText("P2.9");
        jPanel3.add(jButton15);
        jButton15.setBounds(350, 180, 70, 100);

        jButton16.setText("P2.10");
        jPanel3.add(jButton16);
        jButton16.setBounds(450, 180, 70, 100);

        jButton17.setText("P2.2");
        jPanel3.add(jButton17);
        jButton17.setBounds(150, 50, 70, 110);

        jButton18.setText("P2.4");
        jPanel3.add(jButton18);
        jButton18.setBounds(350, 50, 70, 110);

        jButton19.setText("P2.8");
        jPanel3.add(jButton19);
        jButton19.setBounds(250, 180, 70, 100);

        jButton20.setText("P2.1");
        jPanel3.add(jButton20);
        jButton20.setBounds(50, 50, 70, 110);

        jButton43.setText("BOOK");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton43);
        jButton43.setBounds(30, 380, 79, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 420);

        jTabbedPane1.addTab("level2", jPanel3);

        jPanel5.setLayout(null);

        jButton21.setText("P3.7");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton21);
        jButton21.setBounds(150, 180, 70, 100);

        jButton22.setText("P3.6");
        jPanel5.add(jButton22);
        jButton22.setBounds(50, 180, 70, 100);

        jButton23.setText("P3.5");
        jPanel5.add(jButton23);
        jButton23.setBounds(450, 50, 70, 110);

        jButton24.setText("P3.9");
        jPanel5.add(jButton24);
        jButton24.setBounds(350, 180, 70, 100);

        jButton25.setText("P3.2");
        jPanel5.add(jButton25);
        jButton25.setBounds(150, 50, 70, 110);

        jButton26.setText("P3.3");
        jPanel5.add(jButton26);
        jButton26.setBounds(250, 50, 70, 110);

        jButton27.setText("P3.4");
        jPanel5.add(jButton27);
        jButton27.setBounds(350, 50, 70, 110);

        jButton28.setText("P3.8");
        jPanel5.add(jButton28);
        jButton28.setBounds(250, 180, 70, 100);

        jButton29.setText("P3.10");
        jPanel5.add(jButton29);
        jButton29.setBounds(450, 180, 70, 100);

        jButton30.setText("P3.1");
        jPanel5.add(jButton30);
        jButton30.setBounds(50, 50, 70, 110);

        jLabel21.setText("DATE        :");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(254, 330, 80, 20);
        jPanel5.add(jLabel22);
        jLabel22.setBounds(320, 320, 190, 20);

        jLabel25.setText("TIME IN    :");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(254, 360, 80, 20);
        jPanel5.add(jLabel26);
        jLabel26.setBounds(320, 350, 180, 20);

        jLabel27.setText("TIME OUT :");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(250, 390, 80, 20);
        jPanel5.add(jLabel28);
        jLabel28.setBounds(330, 380, 200, 20);
        jPanel5.add(jLabel29);
        jLabel29.setBounds(220, 140, 0, 60);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Select your spot...");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(10, 10, 102, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Locality", "GACCHIBOWLI", "HI TECH", "BANJARA HILLS", "NECKLACE  ROAD" }));
        jPanel5.add(jComboBox3);
        jComboBox3.setBounds(30, 320, 130, 20);

        jButton42.setText("BOOK");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton42);
        jButton42.setBounds(30, 380, 79, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        jPanel5.add(jLabel3);
        jLabel3.setBounds(0, 0, 590, 430);

        jTabbedPane1.addTab("level3", jPanel5);

        jPanel6.setLayout(null);

        jButton31.setText("P4.7");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton31);
        jButton31.setBounds(150, 180, 70, 100);

        jButton32.setText("P4.6");
        jPanel6.add(jButton32);
        jButton32.setBounds(50, 180, 70, 100);

        jButton33.setText("P4.5");
        jPanel6.add(jButton33);
        jButton33.setBounds(450, 50, 70, 110);

        jButton34.setText("P4.9");
        jPanel6.add(jButton34);
        jButton34.setBounds(350, 180, 70, 100);

        jButton35.setText("P4.2");
        jPanel6.add(jButton35);
        jButton35.setBounds(150, 50, 70, 110);

        jButton36.setText("P4.3");
        jPanel6.add(jButton36);
        jButton36.setBounds(250, 50, 70, 110);

        jButton37.setText("P4.4");
        jPanel6.add(jButton37);
        jButton37.setBounds(350, 50, 70, 110);

        jButton38.setText("P4.8");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton38);
        jButton38.setBounds(250, 180, 70, 100);

        jButton39.setText("P4.10");
        jPanel6.add(jButton39);
        jButton39.setBounds(450, 180, 70, 100);

        jButton40.setText("P4.1");
        jPanel6.add(jButton40);
        jButton40.setBounds(50, 50, 70, 110);

        jLabel31.setText("DATE        :");
        jPanel6.add(jLabel31);
        jLabel31.setBounds(254, 330, 80, 20);
        jPanel6.add(jLabel32);
        jLabel32.setBounds(320, 320, 190, 20);

        jLabel33.setText("TIME IN    :");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(254, 360, 80, 20);
        jPanel6.add(jLabel34);
        jLabel34.setBounds(320, 350, 180, 20);

        jLabel35.setText("TIME OUT :");
        jPanel6.add(jLabel35);
        jLabel35.setBounds(250, 390, 80, 20);
        jPanel6.add(jLabel36);
        jLabel36.setBounds(330, 380, 200, 20);
        jPanel6.add(jLabel37);
        jLabel37.setBounds(220, 140, 0, 60);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setText("Select your spot...");
        jPanel6.add(jLabel38);
        jLabel38.setBounds(10, 10, 102, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Locality", "GACCHIBOWLI", "HI TECH", "BANJARA HILLS", "NECKLACE  ROAD" }));
        jPanel6.add(jComboBox4);
        jComboBox4.setBounds(30, 320, 130, 20);

        jButton41.setText("BOOK");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton41);
        jButton41.setBounds(30, 380, 79, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        jPanel6.add(jLabel2);
        jLabel2.setBounds(0, 0, 580, 420);

        jTabbedPane1.addTab("level4", jPanel6);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 590, 450);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 588, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
BOOKED_NEW booked=new BOOKED_NEW();
booked.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
BOOKED_NEW booked=new BOOKED_NEW();
booked.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
BOOKED_NEW booked=new BOOKED_NEW();
booked.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
BOOKED_NEW booked=new BOOKED_NEW();
booked.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PARKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PARKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PARKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PARKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PARKING_NEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
